//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManager_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> OperationId { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Operation Operation { get; set; }
    }
}
